name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # ===============================
    # Checkout koda
    # ===============================
    - name: Checkout repository
      uses: actions/checkout@v4

    # ===============================
    # Docker login (DockerHub)
    # ===============================
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ===============================
    # Build & push Docker images
    # ===============================
    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/config-server:latest ./config-server
        docker push ${{ secrets.DOCKER_USERNAME }}/config-server:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/discovery-server:latest ./discovery-server
        docker push ${{ secrets.DOCKER_USERNAME }}/discovery-server:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ./api-gateway
        docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest ./auth-service
        docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/incident-service:latest ./incident-service
        docker push ${{ secrets.DOCKER_USERNAME }}/incident-service:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/storage-service:latest ./storage-service
        docker push ${{ secrets.DOCKER_USERNAME }}/storage-service:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/moderator-service:latest ./moderator-service
        docker push ${{ secrets.DOCKER_USERNAME }}/moderator-service:latest

        docker build -t ${{ secrets.DOCKER_USERNAME }}/incident-reporting-frontend:latest ./incident-reporting-frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/incident-reporting-frontend:latest

    # ===============================
    # docker-compose + API test
    # ===============================
    - name: Run docker-compose and test API
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        
        MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
        MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
        MINIO_URL: ${{ secrets.MINIO_URL }}
        
        CONFIG_SERVER_URI: ${{ secrets.CONFIG_SERVER_URI }}
        CONFIG_SERVER_GIT_URI: ${{ secrets.CONFIG_SERVER_GIT_URI }}
        CONFIG_SERVER_GIT_USERNAME: ${{ secrets.CONFIG_SERVER_GIT_USERNAME }}
        CONFIG_SERVER_GIT_PASSWORD: ${{ secrets.CONFIG_SERVER_GIT_PASSWORD }}
        
        SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        SPRING_INCIDENT_DATASOURCE_URL: ${{ secrets.SPRING_INCIDENT_DATASOURCE_URL }}
        SPRING_USER_DATASOURCE_URL: ${{ secrets.SPRING_USER_DATASOURCE_URL }}
        SPRING_MODERATOR_DATASOURCE_URL: ${{ secrets.SPRING_MODERATOR_DATASOURCE_URL }}
        
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      run: |
        set +e
        echo "Run docker-compose and test API"
        
        docker compose -f docker-compose.ci.yml up -d
        sleep 5
        
        echo "=== DOCKER PS -A ==="
        docker ps -a
        
        echo "=== CONFIG-SERVER LOGS ==="
        docker compose -f docker-compose.ci.yml logs --no-color config-server
        
        echo "=== DISCOVERY-SERVER LOGS ==="
        docker compose -f docker-compose.ci.yml logs discovery-server
        
        sleep 40
        echo "=== API-GATEWAY LOGS ==="
        docker compose -f docker-compose.ci.yml logs api-gateway
        
        echo "=== AUTH-SERVICE LOGS ==="
        docker compose -f docker-compose.ci.yml logs auth-service
        
        echo "=== STORAGE-SERVICE LOGS ==="
        docker compose -f docker-compose.ci.yml logs storage-service
        
        echo "=== USER-SERVICE LOGS ==="
        docker compose -f docker-compose.ci.yml logs user-service
        
        echo "=== MODERATOR-SERVICE LOGS ==="
        docker compose -f docker-compose.ci.yml logs moderator-service
        
        echo "=== INCIDENT-SERVICE LOGS ==="
        docker compose -f docker-compose.ci.yml logs incident-service
        
        echo "Waiting for API Gateway health..."
        until curl -s http://localhost:8080/actuator/health | grep -q '"status":"UP"'; do
          echo "Gateway not ready yet..."
          sleep 5
        done
        echo "API Gateway is UP"
        
        echo "Testing /api/auth/register"
        while true; do
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            -X POST http://localhost:8080/api/auth/register \
            -H "Content-Type: application/json" \
            -d '{
              "firstName":"test",
              "lastName":"test",
              "username":"test",
              "password":"test"
            }')
            
          BODY=$(echo "$RESPONSE" | head -n -1)
          STATUS=$(echo "$RESPONSE" | tail -n 1)
          
          echo "HTTP STATUS: $STATUS"
          echo "BODY: $BODY"
          
          if [ "$STATUS" = "200" ] || [ "$STATUS" = "201" ] || [ "$STATUS" = "409" ]; then
            echo "Register OK"
            break
          fi
          
          echo "Register not ready, retrying..."
          sleep 5
        done
        
        echo "Testing /api/auth/login"
        while true; do
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            -X POST http://localhost:8080/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{"username":"test","password":"test"}')
            
          BODY=$(echo "$RESPONSE" | head -n -1)
          STATUS=$(echo "$RESPONSE" | tail -n 1)
          
          echo "LOGIN STATUS: $STATUS"
          echo "LOGIN BODY: $BODY"
          
          TOKEN=$(echo "$BODY" | jq -r '.token')
          
          if [ "$STATUS" = "200" ] && [ "$TOKEN" != "null" ] && [ -n "$TOKEN" ]; then
            echo "Login OK"
            break
          fi
          
          echo "Login not ready, retrying..."
          sleep 5
        done
        
        echo "User JWT Token: $TOKEN"
        
        echo "Testing /api/incidents"
        sleep 5
        curl -f -H "Authorization: Bearer $TOKEN" http://localhost:8080/api/incidents
        
        echo "Testing /api/incidents/report"
        sleep 5
        RESPONSE=$(curl -s -w "\n%{http_code}"
          -X POST http://localhost:8080/api/incidents/report \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $TOKEN" \
          -d '{
                "latitude": 44.77588873924588,
                "longitude": 17.19954618465535,
                "type": "POPLAVA",
                "description": "poplava",
                "imageUrl": "poplava.jpg"
              }')
              
        BODY=$(echo "$RESPONSE" | head -n -1)
        STATUS=$(echo "$RESPONSE" | tail -n 1)
        
        echo "REPORT STATUS: $STATUS"
        echo "REPORT BODY: $BODY"
        
        if [ "$STATUS" = "200" ] || [ "$STATUS" = "201" ]; then
          echo "Incident report OK"
        else
          echo "Incident report failed"
        fi